version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sqs-sns-exchange-investigation"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vn6jgi0d56lp"
s3_prefix = "sqs-sns-exchange-investigation"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
